### ISSUE TITLE
Tutorial does not work with current VIP version

### ISSUE THREAD

**Issue by m-samland** [carlgogo/VIP_extras#1]
It seems there have been major changes to the pipeline since the tutorial has been made. It would be great if you someone familiar with the pipeline could write an up-to-date version to make it easier for beginners to use.

**Comment by carlos-gg** [comment]
@m-samland I fully agree with you, the tutorial needs to be updated! I'll find out if there is someone willing to help with that. Otherwise, I'll have to do it myself when I find free time. I'll keep this open.

**Comment by carlos-gg** [comment]
The tutorial has been updated!
